### ISSUE TITLE
decoy diversity loses guarantee

### ISSUE THREAD

**Issue by lan-codes** [molinfo-vienna/CDPKit-Utils#1]
https://github.com/molinfo-vienna/CDPKit-Utils/blob/da40537c986c42343f46a587d5c60c4350d39ce9/gen_decoys.py#L329-L330

The new decoy can have similarity > MAX_DECOY_DECOY_SIM to other decoys in res_decoys.

**Comment by seidelt** [comment]
Hi Lan,

thanks for pointing me to this issue! I have fixed the bug and now all output decoy pairs are **guaranteed** to have a Tc <= 0.8

Best regards,
Thomas

**Comment by lan-codes** [comment]
Hi Thomas,

That is very nice! Thank you!

Best regards,

Lan.
